apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
  namespace: innotter-project
  labels:
    app: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      initContainers:
        - name: init-redis-service
          image: busybox:1.28
          command: [ 'sh', '-c', "until nslookup redis.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for redis-service; sleep 2; done" ]
      containers:
        - name: celery
          image: andreyneveykov/innotter
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "cd src/ && celery -A innotter worker -l info"]
          envFrom:
            - secretRef:
                name: innotter-secret
