version: "3.1"

services:
  web:
#    image: kirylofficial/innotter
    build: ./
    container_name: web
    restart: always
    entrypoint: ./entrypoint.sh web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq3
      - db
      - redis
      - localstack

  db:
    image: postgres:latest
    container_name: db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./entrypoint_localstack.sh:/docker-entrypoint-initaws.d/entrypoint_localstack.sh"

  rabbitmq3:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq3
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build: .
    container_name: celery
    entrypoint: ./entrypoint.sh celery
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq3
      - web

  microservice:
#    image: kirylofficial/microservice
    build: ./src/microservice/
    container_name: microservice
    entrypoint: ./entrypoint_microservice.sh
    restart: always
    volumes:
      - ./src/microservice/:/code/src/microservice/
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - localstack
      - rabbitmq3

volumes:
  pgdata:
