version: "3.1"

services:
  web:
    build: ./
    container_name: web
    restart: always
    volumes:
      - ./src/:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    env_file:
      - .env

volumes:
  pgdata:
