version: "3.1"

services:
  web:
    build: ./
    container_name: web
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    env_file:
      - .env

  redis:
    image: redis
    container_name: redis
    command: redis-server
    ports:
      - "14000:6379"

volumes:
  pgdata:
