version: "3.1"

services:
  web:
    build: ./
    container_name: web
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - localstack
      - rabbitmq3

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    env_file:
      - .env

  redis:
    image: redis
    container_name: redis
    command: redis-server
    ports:
      - "14000:6379"

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./entrypoint_localstack.sh:/docker-entrypoint-initaws.d/entrypoint_localstack.sh"

  rabbitmq3:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq3
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}"
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"

  celery:
    build: .
    container_name: celery
    entrypoint: ./entrypoint_celery.sh
    restart: always
    depends_on:
      - rabbitmq3
      - web

volumes:
  pgdata:
