# Generated by Django 4.1.7 on 2023-05-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="uuid",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
