apiVersion: v1
kind: Secret
metadata:
  name: innotter-secret
  namespace: innotter-project
  labels:
    app: innotter
type: Opaque
data:
  SECRET_KEY:
  DEBUG:
  POSTGRES_DB:
  POSTGRES_USER:
  POSTGRES_PASSWORD:
  POSTGRES_HOST:
  POSTGRES_PORT:
  REDIS_HOST:
  REDIS_PORT:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  HOSTNAME_EXTERNAL:
  PORT_EXTERNAL:
  REGION_NAME:
  BUCKET_NAME:
  EMAIL_HOST_USER:
  DEFAULT_REGION:
  DATA_DIR:
  DYNAMODB_TABLE_NAME:
  RABBITMQ_PROTOCOL:
  RABBITMQ_HOST:
  RABBITMQ_DEFAULT_USER:
  RABBITMQ_DEFAULT_PASS:
  RABBIT_STATISTIC_QUEUE:
