apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  namespace: innotter-project
  labels:
    app: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      initContainers:
        - name: check-rabbitmq-ready
          image: busybox
          command: ['sh', '-c',
                    'until wget http://admin:admin@rabbitmq3:15672/api/aliveness-test/%2F;
                    do echo waiting for rabbitmq; sleep 2; done;']
      containers:
        - name: microservice
          image: andreyneveykov/microservice
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "uvicorn main:app --host 127.0.0.1 --port 8001"]
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: innotter-secret
