apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: innotter-project
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
        - name: init-postgres-service
          image: postgres:latest
          command: [ 'sh', '-c',
            'until pg_isready -h db.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local -p 5432;
          do echo waiting for database; sleep 2; done;' ]
      containers:
        - name: web
          image: kirylofficial/innotter
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "python src/manage.py migrate && python src/manage.py runserver"]
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: innotter-secret
          readinessProbe:
            tcpSocket:
              port: 8000
          livenessProbe:
            tcpSocket:
              port: 8000
            periodSeconds: 15
