apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: innotter-project
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: kirylofficial/innotter
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "python src/manage.py migrate && python src/manage.py runserver"]
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: innotter-secret
