# Generated by Django 4.1.7 on 2023-05-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0003_alter_page_uuid"),
        ("post", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="post", to="page.tag"
            ),
        ),
    ]
