apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq3-deployment
  namespace: innotter-project
  labels:
    app: rabbitmq3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq3
  template:
    metadata:
      labels:
        app: rabbitmq3
    spec:
      hostname: rabbitmq3
      containers:
      - name: rabbitmq3
        image: rabbitmq:3-management-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 5672
        - containerPort: 15672
        envFrom:
          - secretRef:
              name: innotter-secret
